### ISSUE TITLE
Style conflict with GitHub Dark

### ISSUE THREAD

**Issue by DemonWav** [synthtech/github-mod#15]
I don't know how you deal with conflicts here, so let me know if this is better suited on the GitHub Dark issue tracker instead.

When both GitHub Dark and GitHub Mod are applied drop down boxes in the pull request "Files changed" tabs are drawn under the file header. If either is disabled the issue goes away. this happens with both the Diff settings and Review changes drop downs.

![example](https://user-images.githubusercontent.com/1332104/42393999-357c16f4-811e-11e8-80a8-dce6c50b7ac1.png)

**Comment by h404bi** [comment]
Cool! DemonWav the creator of MinecraftDev use GitHub Mod! 💯 

It caused by Github Dark, which modified the z-index of the header of diff-view:
![tim 20180707025933](https://user-images.githubusercontent.com/5764917/42395832-da026e4e-8191-11e8-9cc9-0fd82f3bbab8.png)

See the source of Github Dark:
https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L1279

To resolve this problem, remove the z-index from GitHub Dark. You may file a new issue or pull-request on [GitHub Dark's repository](https://github.com/StylishThemes/GitHub-Dark).

**Comment by synthtech** [comment]
As mentioned above, the snippet GitHub Dark used from the Refined GitHub extension is likely causing the issue you described.

I think adding the following rule to their style could fix it:
```css
.pull-request-tab-content .diff-view .file {
    z-index: 1;
}
```

**Comment by DemonWav** [comment]
Thanks, I'll open an issue for them then.
